
title: Ether's Blog
email: etherlin1@gmail.com
description: A personal blog by Ether Lin

baseurl: "" 
url: "https://etherlin.top/" 
github_username:  Lin-Ether

# Build settings
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
